#include<stdio.h>
int main()
{
    int x,y,Total,Note,Change;
    printf("Enter Drinks Price=");
    scanf("%d",&x);
    printf("Enter Ice Cream Price=");
    scanf("%d",&y);
    printf("Note given=");
    scanf("%d",&Note);
    Total=x+y;
    Change=Note-Total;
    printf("\t    -------SMART POINT-------\n");
    printf("\t     Reliance Retail Limited\n");
    printf("\t        RELIANCE SMART POINT\n");
    printf("\t      Plot No.40(Western Part)\n");
    printf("\t     covered by SY . No . 407\n");
    printf("\t\t  Keesara Mandal\n");
    printf("\t     Medchal malkajgiri District\n");
    printf("\t     Hyderabad..Telangana-501301\n");
    printf("\tCustomer care 18008910001/18001027382\n");
    printf("\t  CIN No : U01100MH1999PLC120563\n");
    printf("\t\tGSTIN-36AABCR1718E1ZQ\n");
    printf("\t   FSSAI Lic No - 13620034000393\n");
    printf("----------------------------------------------------\n  You have saved Rs.\n----------------------------------------------------\n");
    printf("Place of Supply & State Code 36 16\n");
    printf("Customer Type : URD\n");
    printf("\t\t\tTAX INVOICE\n");
    printf("*Original for Recipient\n");
    printf("Date:01-01-2024\t Bill No:92\n");
    printf("Store 0329  Cashier :60643253\n");
    printf("----------------------------------------------------\nHSN Code   Item Description  Net price   Qty   Value\n----------------------------------------------------\n");
    printf("1)CGST $ 2.50  SGST $ 2.50 \n");
    printf("04039090\tDRINKS \t\t\t  1    %d\t\n",x);
    printf(" \n\t\t\t\t%d\n ",x);
    printf("2)CGST $ 2.50  SGST $ 2.50 \n");
    printf("04039091\tICE CREAMS \t\t  1    %d\t\n",y);
    printf(" \n\t\t\t\t%d\n ",y);
    printf("----------------------------------------------------\n");
    printf("Items:2\nTotal Amount paid                           %d\nNet Amount Paid in CASH                     %d\nChange                                       %d\n(AMOUNT INCLUSIVE OF APPLICABLE TAXES)\n",Total,Note,Change);
    printf("----------------------------------------------------\n    ----GST Breakup Deta:15----Amount(INR)----\n----------------------------------------------------\n");
    printf("GST   Taxable   CGST   SGST   CESS   Total Amount\nIND   Amount\n");
    printf("----------------------------------------------------\n 1)\t\t\t\t\t%d\n----------------------------------------------------\n",x);
    printf(" 2)\t\t\t\t\t%d\n----------------------------------------------------\n",y);
    printf("Total\t\t\t\t\t%d\n----------------------------------------------------\n",Total);
    printf("PaymentRefNo# U328106009230122094\nTaxInvoice# U323791279398274\nPone Card No.:76***343\nTerms & Conditions Apply");
    printf("\n----------------------------------------------------\n");
    printf("   ******Thank You for Shopping With us******* ");
    return 0;
}
